/* Proposal: decorative layer only. It never handles checkout or user data. */
(()=>{'use strict';
const img=(name,cls='')=>`<img class="${cls}" src="assets/season/${name}.svg" alt="" draggable="false">`;
const flower=(cls='')=>img('cempasuchil','season-flower '+cls);
const candles=()=>`<div class="season-candles" aria-hidden="true">${[0,1,2].map((_,i)=>`<span class="season-candle candle-${i}"><i class="season-flame"><b></b></i><i class="season-wax"><b></b></i></span>`).join('')}</div>`;
const colors=['naranja','morado','rosa','turquesa'];
const header=document.querySelector('#app .topbar');
const flags=document.createElement('div');flags.className='season-bunting';flags.setAttribute('aria-hidden','true');flags.innerHTML='<span class="season-cord"></span>'+Array.from({length:18},(_,i)=>img('papel-'+colors[i%4],`season-flag flag-${i%4}`)).join('');header.prepend(flags);
const ribbon=document.createElement('section');ribbon.className='season-ribbon';ribbon.setAttribute('aria-label','Edición Halloween y Día de Muertos');
ribbon.innerHTML=`<div class="season-ribbon-left" aria-hidden="true">${flower('flower-a')}${flower('flower-b')}${img('calavera','season-skull')}${flower('flower-c')}</div><div class="season-copy"><span>HALLOWEEN · DÍA DE MUERTOS</span><h2>Una tradición llena de sabor.</h2><p>Cempasúchil, papel picado y luz de velas en Burger Shot.</p></div><div class="season-ribbon-right" aria-hidden="true">${candles()}${flower('flower-d')}${flower('flower-e')}</div>`;header.after(ribbon);
const altar=document.createElement('div');altar.className='season-sidebar';altar.setAttribute('aria-hidden','true');altar.innerHTML=`${flower()}${img('calavera')}<div><b>Día de Muertos</b><small>EDICIÓN ESPECIAL</small></div>`;document.querySelector('.sidebar .store-chip').after(altar);
const order=document.querySelector('.order-head');order.classList.add('season-order-head');const ornament=document.createElement('div');ornament.className='season-order-ornament';ornament.setAttribute('aria-hidden','true');ornament.innerHTML=flower()+img('calavera');order.append(ornament);
const footer=document.createElement('div');footer.className='season-order-foot';footer.setAttribute('aria-hidden','true');footer.innerHTML=flower()+`<span>Hecho para compartir.</span>`+flower();document.querySelector('.order-checkout').append(footer);
const petals=document.createElement('div');petals.className='season-petals';petals.setAttribute('aria-hidden','true');petals.innerHTML=Array.from({length:9},(_,i)=>`<span style="--x:${[3,15,27,38,54,68,77,89,97][i]}%;--delay:-${i*2.2}s;--duration:${17+i%4*3}s;--size:${9+i%3*3}px;--drift:${i%2?'-':'+'}34px">${img('petalo')}</span>`).join('');document.querySelector('#app .main').append(petals);
document.querySelectorAll('.gate-art').forEach(el=>{const decor=document.createElement('div');decor.className='season-gate-ornament';decor.setAttribute('aria-hidden','true');decor.innerHTML=flower()+img('calavera')+flower()+candles();el.append(decor)});
// Celebrate a product click with a brief warm border. No timers or sale logic.
document.addEventListener('click',e=>{const b=e.target.closest('[data-add],[data-add-qty],[data-quick-add]');if(!b)return;const card=b.closest('.product-card');if(card){card.classList.remove('season-added');void card.offsetWidth;card.classList.add('season-added')}});
const settings=document.querySelector('.v6-settings');if(settings){const label=document.createElement('label');label.className='permission-row';label.innerHTML='<span><strong>Pétalos en el ambiente</strong><small>Decoración animada de cempasúchil en los bordes de la página.</small></span><input id="seasonPetalToggle" type="checkbox" checked>';settings.querySelector('h2').after(label);const toggle=label.querySelector('input');try{toggle.checked=localStorage.getItem('bs_season_petals')!=='false'}catch{}const apply=()=>document.body.classList.toggle('season-petals-off',!toggle.checked);apply();toggle.onchange=()=>{apply();try{localStorage.setItem('bs_season_petals',String(toggle.checked))}catch{}}}
})();
