const {PGlite}=require('@electric-sql/pglite');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
  const db=new PGlite();await db.waitReady;
  await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;
    create schema auth;create table auth.users(id uuid primary key,email text);
    create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
    grant usage on schema public,auth to anon,authenticated,service_role;
    grant execute on function auth.uid() to public;
    alter default privileges in schema public grant all on tables to anon,authenticated,service_role;
    alter default privileges in schema public grant all on sequences to anon,authenticated,service_role;
    create publication supabase_realtime;
    create schema storage;create table storage.buckets(id text primary key,name text,public boolean);
    create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);
    alter table storage.objects enable row level security;
    create function storage.foldername(name text) returns text[] language sql immutable as $$select string_to_array(name,'/')$$;
    grant usage on schema storage to anon,authenticated;
    grant select,insert,update,delete on storage.objects to authenticated;grant select on storage.objects to anon;`);
  const root=path.resolve(__dirname,'..');
  for(const f of ['supabase_schema_v3.sql','supabase_patch_v4_2.sql','supabase_patch_v5_1.sql','supabase_patch_v5_2.sql','supabase_patch_v5_4_quantities.sql','supabase_patch_v5_5_employee_week.sql'])await db.exec(fs.readFileSync(path.join(root,f),'utf8').replace('create extension if not exists pgcrypto;',''));
  let count=0;const ok=s=>{count++;console.log('PASS '+s)};
  const ids=['00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000002','00000000-0000-4000-8000-000000000003'];
  for(const id of ids)await db.query('insert into auth.users(id) values($1)',[id]);
  const as=async(id,fn)=>{await db.exec('set role authenticated');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);try{return await fn()}finally{await db.exec('reset role');await db.exec("select set_config('request.jwt.claim.sub','',false)")}};
  const store=(await as(ids[0],()=>db.query("select public.bootstrap_store('BurgerShot','Admin','admin','admin@example.invalid') id"))).rows[0].id;
  const otherStore=(await as(ids[2],()=>db.query("select public.bootstrap_store('Otra','Otro','otro','otro@example.invalid') id"))).rows[0].id;
  await db.query("insert into public.profiles(user_id,store_id,name,role,can_manage_employees) values($1,$2,'Empleado','cashier',true)",[ids[1],store]);
  await as(ids[0],()=>db.query("insert into public.employee_of_week(store_id,employee_id,week_start) values($1,$2,'2026-09-14')",[store,ids[1]]));
  assert.equal((await as(ids[1],()=>db.query('select * from public.employee_of_week'))).rows.length,1);ok('Administrador configura y empleado de la misma tienda puede leer');
  assert.equal((await as(ids[1],()=>db.query("update public.employee_of_week set photo_url='https://example.invalid/no.jpg' returning *"))).rows.length,0);
  assert.equal((await as(ids[1],()=>db.query('delete from public.employee_of_week returning *'))).rows.length,0);ok('Permiso gestionar empleados no permite editar ni borrar el reconocimiento');
  assert.equal((await as(ids[2],()=>db.query('select * from public.employee_of_week'))).rows.length,0);
  await assert.rejects(as(ids[2],()=>db.query("insert into public.employee_of_week(store_id,employee_id,week_start) values($1,$2,'2026-09-14')",[store,ids[1]])),/row-level security/);ok('Otra tienda no puede leer ni configurar el reconocimiento');
  await assert.rejects(as(ids[0],()=>db.query('update public.employee_of_week set employee_id=$1',[ids[2]])),/row-level security/);ok('No se puede seleccionar un empleado de otra tienda');
  await as(ids[0],()=>db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['employee-week',store+'/foto.webp']));
  assert.equal((await as(ids[0],()=>db.query('update storage.objects set name=$1 returning *',[store+'/nueva.webp']))).rows.length,1);ok('Admin sube y reemplaza fotos en su carpeta');
  await assert.rejects(as(ids[1],()=>db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['employee-week',store+'/no.webp'])),/row-level security/);
  assert.equal((await as(ids[1],()=>db.query('delete from storage.objects returning *'))).rows.length,0);ok('Empleado no puede subir ni borrar fotos');
  await assert.rejects(as(ids[2],()=>db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['employee-week',store+'/no.webp'])),/row-level security/);
  await assert.rejects(as(ids[0],()=>db.query('update storage.objects set name=$1',[otherStore+'/no.webp'])),/row-level security/);ok('Fotos no se pueden escribir ni mover a carpetas ajenas');
  await db.exec('set role anon');await assert.rejects(db.query('select * from public.employee_of_week'),/permission denied/);await db.exec('reset role');ok('Sin sesión no se puede leer el reconocimiento');
  await db.exec(fs.readFileSync(path.join(root,'supabase_patch_v5_5_employee_week.sql'),'utf8'));
  assert.equal((await db.query('select * from public.employee_of_week')).rows.length,1);ok('Parche repetible conserva la configuración');
  await db.close();console.log(`${count} pruebas V5.5 SQL superadas; Storage y Auth simulados, sin base real.`);
})().catch(e=>{console.error(e);process.exit(1)});
