const {JSDOM,VirtualConsole}=require('jsdom');const fs=require('fs');const assert=require('node:assert/strict');
const base=__dirname+'/../',wait=()=>new Promise(r=>setTimeout(r,55));let passed=0;const ok=s=>{passed++;console.log('PASS '+s)};
async function setup(edit=()=>{}){const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>{if(!e.message.includes('CSS'))errors.push(e.message)});const dom=new JSDOM(fs.readFileSync(base+'index.html','utf8'),{url:'https://demo.invalid/',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc});const w=dom.window;w.confirm=()=>true;for(const f of ['demo/mock-supabase.js','demo/data.js'])w.eval(fs.readFileSync(base+f,'utf8'));edit(w.fixture);for(const f of ['companion-core.js','companion.js','v6-core.js','v6-modules.js','app.js'])w.eval(fs.readFileSync(base+f,'utf8'));await wait();const $=s=>w.document.querySelector(s),click=s=>{assert.ok($(s),s);$(s).click()},fill=(s,v)=>{$(s).value=v;$(s).dispatchEvent(new w.Event('input',{bubbles:true}));};return{dom,w,$,click,fill,errors}}
(async()=>{
const t=await setup();const {w,$,click,fill}=t;assert.deepEqual(t.errors,[]);assert.equal($('#app').classList.contains('hidden'),false);ok('V6 inicia con sesión existente y módulos nuevos');
click('[data-page="administration"]');assert.equal($('#adminsBody').children.length,5);assert.match($('#adminsBody').textContent,/Gerente/);fill('#adminSearch','maria');assert.equal($('#adminsBody').children.length,1);ok('Tabla administrativa, roles, correos y búsqueda');
click('[data-admin-tab="roles"]');assert.ok($('#rolePermissions [data-perm="manage_customers"]'));click('[data-role="admin"]');assert.equal($('#saveRoleBtn').disabled,true);ok('Matriz editable y administrador protegido');
click('[data-page="loyalty"]');assert.equal($('#loyaltyBody').children.length,4);click('#newCustomerBtn');fill('#cName','<script>alert(1)</script>');fill('#cIdentifier','TEST-21');$('#v6Form').dispatchEvent(new w.Event('submit',{cancelable:true}));await wait();assert.ok(w.fixture.db.customers.some(c=>c.identifier==='TEST-21'));assert.equal($('#loyaltyBody script'),null);ok('Ficha de cliente guarda y escapa contenido HTML');
click('[data-page="promotions"]');assert.equal($('#promoCards').children.length,3);click('[data-promo-pause="promo-1"]');await wait();assert.equal(w.fixture.db.promotions[0].active,false);click('[data-promo-pause="promo-1"]');await wait();ok('Promociones se pueden pausar y reactivar');
click('[data-page="pos"]');click('[data-add="p0"]');fill('#couponCode','NOCHE15');click('#applyCouponBtn');assert.equal($('#grandTotal').textContent,'$238');assert.equal($('#discountSelect').disabled,true);fill('#orderClient','SOFIA-24');click('#checkoutBtn');assert.equal($('#saleClient').value,'SOFIA-24');click('#confirmSaleBtn');await wait();const sale=w.fixture.db.sales.find(s=>s.promotion_id==='promo-1');assert.ok(sale);assert.equal(sale.total,238);assert.equal(sale.discount_id,null);assert.equal($('#couponCode').value,'');ok('Cupón, total, identificación y registro integrados en caja');
assert.deepEqual(t.errors,[]);t.dom.window.close();
const denied=await setup(f=>{f.db.profiles[0].role='cashier';Object.keys(f.db.profiles[0]).filter(k=>k.startsWith('can_')).forEach(k=>f.db.profiles[0][k]=false)});denied.click('[data-page="administration"]');assert.equal(denied.$('#page-administration').classList.contains('active'),false);assert.equal(denied.$('#applyCouponBtn').disabled,true);denied.click('[data-page="promotions"]');assert.equal(denied.$('#page-promotions').classList.contains('active'),false);denied.dom.window.close();ok('Accesos y cupones bloqueados para usuario sin permisos');
const missing=await setup(f=>f.failTable='promotions');assert.equal(missing.$('#app').classList.contains('hidden'),false);missing.click('[data-page="pos"]');missing.click('[data-add="p0"]');assert.equal(missing.$('#grandTotal').textContent,'$280');assert.equal(missing.$('#applyCouponBtn').disabled,true);assert.match(missing.$('#v6Status').textContent,/supabase_patch_v6/);assert.deepEqual(missing.errors,[]);missing.dom.window.close();ok('V5 sigue cobrando si falta migración V6; aviso visible');
const core=require('../v6-core');assert.equal(core.discount({kind:'two_for_one'},[{id:'a',qty:3,price:100,tag:'all'},{id:'b',qty:1,price:90,tag:'all'}]),100);assert.equal(core.discount({kind:'fixed',value:9999},[{id:'a',qty:1,price:100,tag:'none'}]),0);assert.equal(core.status({active:true,ends_at:'2000-01-01'}),'Expirada');ok('Reglas de pares, exclusiones y vencimiento');
fs.writeFileSync(__dirname+'/v6-ui-results.json',JSON.stringify({passed,environment:'JSDOM + Supabase simulado; no remoto'},null,2));console.log(passed+' comprobaciones V6 UI superadas');
})().catch(e=>{console.error(e);process.exit(1)});
