const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');const assert=require('assert/strict'),fs=require('fs');
const server=require('child_process').spawn('python',['-m','http.server','8000','--bind','127.0.0.1'],{cwd:__dirname+'/..',stdio:'ignore'});
(async()=>{await new Promise(r=>setTimeout(r,500));const b=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage']});const page=await b.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto('http://127.0.0.1:8000/DEMO_V6.html');await page.locator('#app').waitFor({state:'visible'});fs.mkdirSync(__dirname+'/../preview',{recursive:true});
async function shot(name){await page.waitForTimeout(350);await page.screenshot({path:__dirname+'/../preview/'+name+'.png',fullPage:true})}
await page.locator('[data-page="pos"]').click();await page.locator('[data-add="p0"]').click();await page.locator('#orderClient').fill('SOFIA-24');await page.locator('#couponCode').fill('NOCHE15');await page.locator('#applyCouponBtn').click();await page.locator('#toastHost').evaluate(e=>e.innerHTML='');assert.equal(await page.locator('#grandTotal').textContent(),'$238');await shot('01-caja');
await page.locator('[data-page="administration"]').click();await shot('02-administracion');await page.locator('[data-admin-tab="roles"]').click();await shot('03-permisos');
await page.locator('[data-page="promotions"]').click();await shot('04-promociones');await page.locator('#newPromoBtn').click();await page.locator('#pName').fill('Promo de prueba');await page.locator('#pValue').fill('10');await page.locator('#v6Submit').click();await page.waitForTimeout(200);assert.ok(await page.locator('#promoCards').innerText().then(t=>t.includes('Promo de prueba')));
await page.locator('[data-page="loyalty"]').click();await shot('05-clientes');
await page.setViewportSize({width:390,height:844});await page.locator('#mobileMenu').click();await page.locator('[data-page="pos"]').click();await shot('06-movil');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile horizontal overflow');await page.locator('#checkoutBtn').scrollIntoViewIfNeeded();await page.locator('#checkoutBtn').click();assert.equal(await page.locator('#saleClient').inputValue(),'SOFIA-24');await page.locator('#confirmSaleBtn').click();await page.waitForTimeout(200);assert.equal(await page.locator('#checkoutModal').evaluate(e=>e.classList.contains('hidden')),true);assert.deepEqual(errors,[]);
fs.writeFileSync(__dirname+'/visual-results.json',JSON.stringify({desktop:'1440x1000',mobile:'390x844',horizontalOverflow:false,pageErrors:errors,flows:['navegación','cupón y cobro en móvil','crear promoción','tabla administrativa','roles'],environment:'Chromium headless + datos simulados; no cuenta real'},null,2));console.log('PASS Desktop/mobile, no overflow, no JS errors, coupon checkout and promotion create');await b.close();server.kill();})().catch(e=>{console.error(e);server.kill();process.exit(1)});
