// Demonstration only: in-memory records, no network connection and no real sales.
window.BURGERSHOT_DEMO=true;
(function(){
 const f=window.fixture,sid='store-1',now=new Date();
 const perms={edit_orders:true,manage_catalog:true,manage_employees:true,view_reports:true,manage_payouts:true,view_audit:true,manage_customers:true,manage_promotions:true,apply_promotions:true};
 f.db.pos_roles=[['admin','Administrador',{}],['manager','Gerente',perms],['supervisor','Supervisor',{edit_orders:true,view_reports:true,manage_customers:true,apply_promotions:true}],['cashier','Cajero',{apply_promotions:true}]].map(([key,name,permissions])=>({id:'role-'+key,store_id:sid,key,name,permissions}));
 const people=[['Alex Rivera','alex','admin'],['María López','maria','cashier','manager'],['Diego Cruz','diego','cashier','supervisor'],['Valeria Torres','valeria','cashier','cashier'],['Daniel García','daniel','cashier','cashier']];
 f.db.profiles=people.map(([name,username,role,preset],i)=>({user_id:i===0?'admin-1':i===1?'cashier-1':'user-'+i,store_id:sid,name,username,login_email:username+'@ejemplo.invalid',role,access_role_id:preset?'role-'+preset:null,active:i!==4,commission_percent:15,last_access_at:new Date(now.getTime()-i*3600000).toISOString(),...Object.fromEntries(Object.entries(preset?f.db.pos_roles.find(r=>r.key===preset).permissions:perms).map(([k,v])=>['can_'+k,v]))}));
 f.db.customers=[['Sofía Hernández','SOFIA-24','VIP','Cupón NOCHE15'],['Marco Velázquez','MARCO-12','Frecuente',''],['Carolina Reyes','CARO-08','Convenio','Redline Mechanics'],['Luis Mendoza','LUIS-41','Nuevo','']].map(([name,identifier,level,benefit],i)=>({id:'customer-'+i,store_id:sid,name,identifier,level,benefit,phone:'',notes:'',created_at:now.toISOString()}));
 f.db.promotions=[{id:'promo-1',name:'Una noche con mucho sabor',kind:'percent',value:15,code:'NOCHE15',description:'15% en productos elegibles del menú durante octubre.',product_id:null,active:true},{id:'promo-2',name:'El segundo helado va por nosotros',kind:'two_for_one',value:0,code:null,product_id:'p9',description:'Dos helados, una buena excusa para volver.',active:true},{id:'promo-3',name:'Combo de medianoche',kind:'combo',value:249,code:null,product_id:'p0',description:'Tu combo favorito a precio especial.',active:false}].map(p=>({...p,store_id:sid,starts_at:new Date(now.getTime()-86400000*2).toISOString(),ends_at:new Date(now.getTime()+86400000*25).toISOString()}));
 f.db.sales=Array.from({length:24},(_,i)=>{const person=f.db.profiles[1+i%3],c=f.db.customers[i%4],p=f.db.products[i%4],qty=i%3+1,total=p.price*qty;return{id:'sale-'+i,sale_number:1048-i,store_id:sid,created_by:person.user_id,employee_name:person.name,client:c.identifier,client_type:'general',payment:'Efectivo',total,subtotal:total,discount_name:'Sin convenio',discount_amount:0,commission_percent:15,employee_earnings:total*.15,business_net:total*.85,status:'active',items:[{id:p.id,name:p.name,price:p.price,qty,lineTotal:total}],created_at:new Date(now.getTime()-i*2700000).toISOString(),payout_id:null}});
 f.db.audit_events=[['profiles','Inicio de sesión','login'],['products','Combo Hamburguesa','update'],['promotions','Una noche con mucho sabor','insert'],['pos_roles','Supervisor','update']].map(([entity,entity_name,action],i)=>({id:'event-'+i,store_id:sid,actor_id:'admin-1',actor_name:'Alex Rivera',entity,entity_name,entity_id:'demo-'+i,action,created_at:new Date(now.getTime()-i*3600000).toISOString(),before_data:action==='update'?{name:entity_name}:null,after_data:{name:entity_name}}));
 document.addEventListener('DOMContentLoaded',()=>{
 const bar=document.createElement('div');bar.className='v6-demobar';bar.innerHTML='VISTA PREVIA INTERACTIVA · Datos de ejemplo · No registra ventas reales <button id="demoReset">Restablecer</button>';
 document.querySelector('main').prepend(bar);document.getElementById('demoReset').onclick=()=>location.reload();
 });
})();
